### ISSUE TITLE
Show more than 10 users

### ISSUE THREAD

**Issue by 24hoursmedia-craftcms** [vardump-de/activeusers#1]
Nice plugin, but the number of active users shown in the widget is limited to 10.
Can you make that a configuration setting, and perhaps make the list in the widget scrollable (max-height = ... with overflow: auto) or something?

Thank you

**Comment by rmdev** [comment]
We also thought of that and have it on our "roadmap".

**Comment by rmdev** [comment]
fixed in version 1.1.1
