### ISSUE TITLE
Link to user admin panel or custom url

### ISSUE THREAD

**Issue by 24hoursmedia-craftcms** [vardump-de/activeusers#2]
it would be a nice feature if one could link the user in the widget to the 'user edit' page in the CP,
or even nicer if you could link to a custom url with target is _blank
(i.e. link to https://www.mysite.com/profiles/{user.uid}  or https://www.mysite.com/profiles/{user.username}
)

**Comment by rmdev** [comment]
Nice feature. 
Will be implemented.

**Comment by rmdev** [comment]
fixed in version 1.1.1
